### ISSUE TITLE
local.css issues; table issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/wilkie-collins_no-name#2]
1. When styling the `<table>` tag, don't use the shortcut `border` property, which assigns a color. Instead, leave the color undefined, and use the longhand `border-style` and `border-width` properties. This way, reading systems use a default color (which is usually black anyway) but we gain the ability to let them change the color if entering night mode.
2. I see ALL CAPS in that table in the XHTML file, let's convert those to small caps
3.  In that table, there's use of an `alignright` class.  But, those items are actually just sub-tables, so you should use a sub-`<table>` tag to style them.  You can remove the unsemantic `alignright` and do a clever selector like `table table td:last-child{ text-align: right; }`
4. In that table, it says "7 pounds 10s"; is the word "pounds" in the page scans, or is it the GBP pound symbol? (I ask because in many PG transcriptions they were too lazy to use the pound symbol so they quietly transcribed it as the word "pounds"; we should try to be faithful to the source here if it's necessary, but leave it if not)
5. For the `business-card` class, you can enclose that `<p>` tag in a `<blockquote class="business-card">`. This is slightly more semantically accurate (as they are presenting a specially styled block quotation) and we get a nice margin on it for free.

**Comment by acabal** [comment]
- On line 59, don't create custom margins for letters (which I assume are all a `<blockquote>`); to remove the margins, you can target the specific properties to remove instead of both removing them and changing the defaults of the others.  For example instead of the shorthand `margin: 1.5em 0 0 1em;` property, do `margin-left: 0; margin-right: 0;`
- Likewise, remove the custom margin from line 38 `z3998:diary-entry` as `<blockquote>` already includes a 1em margin by default; let's not change the spacing rhythm with custom margins here.
- The blocks at 52 and 77 are duplicates, you can remove one or the other block. However please remove the .5em bottom margin there, again to help maintain a more regular rhythm.

**Comment by acabal** [comment]
- Remove `class="dedication"` from the `<p>` tag in `dedication.xhtml`, it seems to be unused. (You correctly targeted the `<p>` tag based on its parent's `epub:type` instead of using an unnecessary class.)

**Comment by drgrigg** [comment]
I'm referencing your points as (1) to (9).
(1) Thanks for this, fixed.
(2) I've surrounded Wragge with <b></b> and changed the style in CSS to be small-caps rather than all-small-caps. I wasn't sure about the latter anyway in references like POISON.
(3) Nested tables takes me right back to my days coding in the 1990s! But it does work neatly. I had to change the styling of the nested table though to remove borders and ensure full-width was used. Hope I've done this correctly. My CSS skills are a bit deficient still (will try to educate myself).
(4) Gutenberg was to blame. Changed to £ throughout. Also in the scans, I noticed that the (s) for shillings is italicised, so I've done that to match. (Should that s. for shillings also be surrounded by <abbr>? Seems a bit excessive.)
(5) OK, thanks.
(6) OK
(7) OK
(8) They aren't actually duplicates. One targets se:diary.dateline, the other se:letter.dateline and need to be styled differently.
(9) Thanks, an oversight on my part.
