### ISSUE TITLE
Missing spaces in between-the-scenes-6.xhtml

### ISSUE THREAD

**Issue by acabal** [drgrigg/wilkie-collins_no-name#3]
In some of the letters, the salutations are missing a space before the text.  Not sure if this occurs elsewhere, a quick regex check across the project would be in order.

**Comment by drgrigg** [comment]
Gosh, thanks for spotting this, I've gone through and manually checked every reference (regex was too tricky due to nested spans), finding a lot in many of the letter sections. But what follows the salutation in the page scans is not a space but a dash. Gutenberg has an em-dash. Should there be a space or a hair-space following such dashes in these circumstances? I'm tempted to think so, but the Typography manual doesn't specify.

**Comment by acabal** [comment]
No, an em dash is fine with no space at all.  `typogrify` will remove spaces around em dashes if you put them in. (I think it says in the typography manual not to put spaces around dashes, but if not then that's something I should put in there since `typogrify` applies that rule.
